// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Json;
//
//    var zone = Zone.FromJson(jsonString);

namespace Json
{
    using System;
    using System.Globalization;
    using System.Collections.Generic;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Zone
    {
        [JsonProperty("zones")]
        public Dictionary<string, ZoneValue> Zones { get; set; }
    }

    public partial class ZoneValue
    {
        [JsonProperty("files")]
        public Files Files { get; set; }

        [JsonProperty("shortname", NullValueHandling = NullValueHandling.Ignore)]
        public string Shortname { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? Id { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("expansion", NullValueHandling = NullValueHandling.Ignore)]
        public string Expansion { get; set; }
    }

    public partial class Files
    {
        [JsonProperty("mesh")]
        public Mesh Mesh { get; set; }
    }

    public partial class Mesh
    {
        [JsonProperty("link")]
        public Uri Link { get; set; }

        [JsonProperty("hash")]
        public string Hash { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }
    }

    public partial class Zone
    {
        public static Zone FromJson(string json) => JsonConvert.DeserializeObject<Zone>(json, Json.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Zone self) => JsonConvert.SerializeObject(self, Json.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
